#!/bin/bash

bool=true # print "Nothing to do"
while read line
do
    if [[ "$line" =~ ^#.* ]] || [[ "$line" == "" ]]; then continue; fi
    
    date=$(echo "$line" | sed -e "s@/@ @"| awk '{printf "%s/%s",$2,$1}')
    date_fr=$(echo "$line" | awk '{printf $1}')
    diff=$(echo "$line" | awk '{print $2,$3}')
    action=$(echo "$line" | cut -d ' ' -f4-)
    
    timestamp_today=$(date -d "today 00:00:00" +"%s")
    timestamp_date=$(date -d "$date" +"%s")
    timestamp_diff_date=$(date -d "$date $diff" +"%s")

    if [ $timestamp_today -ge $timestamp_diff_date ] && [ $timestamp_today -le $timestamp_date ];
    then
        bool=false
        time_left=$(( ($timestamp_date - $timestamp_today)/(60*60*24) ))
        
        if [[ $time_left -le 3 ]] && [[ $time_left -gt 1 ]]; then echo -n '${color1}'; fi
        if [[ $time_left -le 1 ]]; then echo -n '${color0}'; fi
        
        echo -n "In $time_left Days : $date_fr - $action";
        
        if [[ $time_left -le 1 ]]; then echo -n '${color}'; fi
        if [[ $time_left -le 3 ]] && [[ $time_left -gt 1 ]]; then echo -n '${color}'; fi
        
        echo 
    fi
done < ~/.conky/calendar.txt

if $bool ; then echo "Nothing to do"; fi